[project]
name = "padel-vision"
version = "0.1.0"
description = "Computer vision applied to padel"
requires-python = ">=3.14"
dependencies = [
    "ultralytics>=8.3.241",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
